app/Http/routes.php
<?php

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::post('/image/{id}/share', [
    'as' => 'shareImage',
    'uses' => 'ClientController@postShareImage'
]);

Route::post('/i-really-want-to-click', [
    'as' => 'wantToClick',
    'uses' => 'ClientController@postClick'
]);

Route::post('/es-loti-gribu-nospiest', [
    'as' => 'gribuNospiest',
    'uses' => 'ClientController@postClick'
]);

Route::post('/contact-form', [
    'as' => 'contactForm',
    'uses' => 'ClientController@postContactForm'
]);

Route::get('/login', [
    'as' => 'loginScreen',
    'uses' => 'AdminController@getLogin'
]);


Route::group([
    'prefix' => 'admin',
    'middleware' => [
        'auth'
    ],
    'namespace' => 'Admin'
], function () {
    Route::get('/', [
        'as' => 'adminMain',
        'uses' => 'AdminController@getMain'
    ]);
    Route::get('/images', [
        'as' => 'adminImages',
        'uses' => 'AdminController@getImages'
    ]);
    Route::get('/categories', [
        'as' => 'adminCategories',
        'uses' => 'AdminController@getCategories'
    ]);
    Route::post('/upload', [
        'as' => 'adminUpload',
        'uses' => 'AdminController@postUploadImage'
    ]);
    Route::post('/change-ordering', [
        'as' => 'adminChangeOrdering',
        'uses' => 'AdminController@postChangeOrdering'
    ]);
    Route::get('/about', [
        'as' => 'adminGetAbout',
        'uses' => 'AdminController@getAbout'
    ]);
    Route::post('/about', [
        'as' => 'adminChangeAbout',
        'uses' => 'AdminController@postChangeAbout'
    ]);

    Route::post('/images/change-album', [
        'as' => 'adminChangeAlbum',
        'uses' => 'AdminController@postChangeAlbum'
    ]);

    Route::get('/images/{id}/delete', [
        'as' => 'adminDeleteImage',
        'uses' => 'AdminController@getImageDelete'
    ]);

    Route::post('/albums/create', [
        'as' => 'adminCreateAlbum',
        'uses' => 'AdminController@postCreateAlbum'
    ]);

    Route::get('/albums/{id}/delete', [
        'as' => 'adminDeleteAlbum',
        'uses' => 'AdminController@getDeleteAlbum'
    ]);

});

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('/', [
        'as' => 'home',
        'uses' => 'ClientController@getHome'
    ]);

    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Route::get('/vylcans', [
        'as' => 'about',
        'uses' => 'ClientController@getAbout'
    ]);
    Route::get('/{slug}', [
        'as' => 'openedContent',
        'uses' => 'ClientController@getCategoryOrImage'
    ]);
});

app/Models/Image.php
<?php

namespace App\Models;

use Intervention\Image\Constraint;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Intervention\Image\Facades\Image as InterventionImage;

class Image extends BaseModel
{

    const TYPE_ALBUM_IMAGE = 0;
    const TYPE_AUTHOR_IMAGE = 1;
    const UPLOAD_PATH = '/images/uploads';
    const THUMB_PREFIX = 'thumb_';

    const ORIENTATION_PORTRAIT = 0;
    const ORIENTATION_LANDSCAPE = 1;
    const ORDER_BY = 'ordering';
    const SHARE_FACEBOOK = 0;
    const SHARE_TWITTER = 1;
    const SHARE_PINTEREST = 2;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'images';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'filename',
        'published',
        'ordering',
        'album_id',
        'views',
        'last_viewed_at',
        'orientation',
        'fb_share',
        'tw_share',
        'pinterest_share',
        'referrer'
    ];

    /*
     * Belongs To
     */
    public function album()
    {
        return $this->belongsTo('App\Models\Album');
    }

    /*
     * Has Many
     */
    public function slugs()
    {
        return $this->hasMany('App\Models\Slug');
    }

    public function getSource($thumbnail = false)
    {
        $image = $this->filename;
        if ($thumbnail) {
            $image = self::THUMB_PREFIX . $image;
        }

        return asset(self::UPLOAD_PATH . '/' . $image);
    }

    /**
     * @param UploadedFile $file
     * @param string $uploadPath
     * @param int $albumId
     * @param array $slugs
     * @return string|Image
     */
    public static function uploadImage(UploadedFile $file, $uploadPath, $albumId, $slugs = [])
    {
        $albumImage = $file->type == self::TYPE_ALBUM_IMAGE;

        $filename = self::createFilename();

        if (!$albumImage) {
            //profile image
            self::createProfileImage($file, $uploadPath, $filename);
        } else {
            //album image
            self::createAlbumImage($file, $uploadPath, $filename, $albumId, $slugs);
        }

        return $filename;
    }

    /**
     * @param UploadedFile $file
     * @param $uploadPath
     * @param $filename
     */
    public static function createProfileImage(UploadedFile $file, $uploadPath, $filename)
    {
        $image = InterventionImage::make($file->getRealPath());
        $image->resize(900, null, function (Constraint $constraint) {
            $constraint->aspectRatio();
        })
            ->save($uploadPath . '/' . $filename);
    }

    /**
     * @param UploadedFile $file
     * @param $uploadPath
     * @param $filename
     * @param $albumId
     * @param array $slugs
     */
    public static function createAlbumImage(UploadedFile $file, $uploadPath, $filename, $albumId, $slugs = [])
    {
        $canvasMaxWidth = 1000;
        $canvasMaxHeight = 800;
        $sideWidth = 20;
        $bottomHeight = 100;

        $orientation = self::ORIENTATION_LANDSCAPE;

        $landscape = true;

        $image = InterventionImage::make($file->getRealPath());

        $currentImageWidth = $image->width();
        $currentImageHeight = $image->height();

        if ($currentImageWidth < $currentImageHeight) {
            $landscape = false;
        }

        $watermarkY = 10;
        $watermarkX = 0;

        $ratio = $currentImageWidth / $currentImageHeight;
        if ($landscape) {
            //landscape

            $imageWidth = $canvasMaxWidth - $sideWidth * 2;
            $imageHeight = null;

            $canvasHeight = ($canvasMaxWidth / $ratio) + $bottomHeight + $sideWidth;
            $canvasWidth = $canvasMaxWidth;

        } else {
            //portrait

            $imageHeight = $canvasMaxHeight - $sideWidth - $bottomHeight;
            $imageWidth = null;

            $canvasHeight = $canvasMaxHeight;
            $canvasWidth = $canvasMaxHeight * $ratio;

            $orientation = self::ORIENTATION_PORTRAIT;

            $watermarkY = 0;
        }

        //lets create canvas on size 900 x 900
        $canvas = InterventionImage::canvas($canvasWidth, $canvasHeight, '#ffffff');

        $watermark = InterventionImage::make(public_path('images/' . 'watermark.png'))
            ->resize(150, null, function (Constraint $constraint) {
                $constraint->aspectRatio();
            })
            ->opacity(70);

        $image->resize($imageWidth, $imageHeight, function (Constraint $constraint) {
            $constraint->aspectRatio();
        })
            ->sharpen(3)
        ;

        $canvas->insert($image, 'top', $sideWidth, $sideWidth)
            ->insert($watermark, 'bottom-right', $watermarkX, $watermarkY)
            ->save($uploadPath . '/' . $filename);


        //creating thumbnail
        InterventionImage::make($file->getRealPath())->fit(300, 300)
            ->save($uploadPath . '/' . self::THUMB_PREFIX . $filename);

        /**
         * @var Image $image
         */
        $image = self::create([
            'filename' => $filename,
            'published' => false,
            'ordering' => self::getNewOrdering($albumId),
            'album_id' => $albumId,
            'orientation' => $orientation
        ]);

        foreach ($slugs as $languageId => $slug) {
            $image->slugs()->create([
                'name' => $slug . '_' . str_replace('.jpg', '', $filename),
                'language_id' => $languageId
            ]);
        }

    }

    /**
     * @param null $additional
     * @return string
     */
    public static function createFilename($additional = null)
    {
        $filename = (string)(time() . rand(1000, 9999));
        if (!is_null($additional)) {
            $filename .= $additional;
        }

        $filename = $filename . '.jpg';

        $exists = Image::where('filename', '=', $filename)->exists();
        if ($exists) {
            return self::createFilename(rand(1000, 9999));
        }

        return $filename;
    }

    /**
     * Deletes image file
     */
    public function deleteFile()
    {
        $filename = $this->filename;
        $file = public_path((Image::UPLOAD_PATH . '/' . $filename));
        $thumbnail = public_path((Image::THUMB_PREFIX . '/' . Image::UPLOAD_PATH . '/' . $filename));

        if (!is_null($filename) and is_file($file)) {
            unlink($file);
        }

        if (!is_null($thumbnail) and is_file($thumbnail)) {
            unlink($thumbnail);
        }
    }

    /**
     * @return null|string
     */
    public function getNextGalleryItemUrl()
    {
        $nextImageUrl = $this->getNextImageUrl();

        if (!is_null($nextImageUrl)) {
            return $nextImageUrl;
        }

        return $this->getFirstAlbumImageUrl();
    }

    /**
     * @return null|string
     */
    public function getPrevGalleryItemUrl()
    {
        $prevImageUrl = $this->getPrevImageUrl();

        if (!is_null($prevImageUrl)) {
            return $prevImageUrl;
        }

        return $this->getLastAlbumImageUrl();
    }

    /**
     * @return null|string
     */
    public function getNextImageUrl()
    {
        $ordering = self::ORDER_BY;
        $nextImageOrdering = self::where($ordering, '>', $this->$ordering)
            ->where('album_id', '=', $this->album_id)
            ->min('ordering');

        if ($nextImageOrdering) {

            $image = self::where('album_id', '=', $this->album_id)
                ->where('ordering', '=', $nextImageOrdering)
                ->first();

            if ($image) {
                return $image->getUrl();
            }
        }

        return null;
    }

    /**
     * @return null|string
     */
    public function getPrevImageUrl()
    {
        $ordering = self::ORDER_BY;
        $prevImageOrdering = self::where($ordering, '<', $this->$ordering)
            ->where('album_id', '=', $this->album_id)
            ->max('ordering');

        if (!is_null($prevImageOrdering)) {
            $image = self::where('album_id', '=', $this->album_id)
                ->where('ordering', '=', $prevImageOrdering)
                ->first();

            if ($image) {
                return $image->getUrl();
            }
        }

        return null;
    }

    public function getFirstAlbumImageUrl()
    {
        $ordering = self::ORDER_BY;
        $image = self::where('album_id', '=', $this->album_id)
            ->where('id', '!=', $this->id)
            ->orderBy($ordering, 'asc')
            ->first();

        if ($image) {
            return $image->getUrl();
        }

        return null;
    }

    public function getLastAlbumImageUrl()
    {
        $ordering = self::ORDER_BY;
        $image = self::where('album_id', '=', $this->album_id)
            ->where('id', '!=', $this->id)
            ->orderBy($ordering, 'desc')
            ->first();

        if ($image) {
            return $image->getUrl();
        }

        return null;
    }

    public function getUrl()
    {
        return route('openedContent', ['slug' => $this->slugByLocale()]);
    }

    public function increaseShare($media)
    {
        $field = 'fb_share';
        if ($media == self::SHARE_TWITTER) {
            $field =  'tw_share';
        }

        if ($media == self::SHARE_PINTEREST) {
            $field = 'pinterest_share';
        }

        $this->update([
            $field => $this->$field + 1
        ]);
    }

    public function getLastViewedDate()
    {
        $env = env('APP_ENV');

        $date = new \DateTime($this->last_viewed_at);

        if ($env == 'server') {
            $date->modify('+2 hours 35 minutes');
        }

        return $date->format('H:i d.m.Y');
    }

    public function updateReferrer($referrer)
    {
        $this->update([
            'referrer' => $referrer
        ]);
    }
}

resources/views/admin/about.blade.php
@extends('admin.app')
@section('content')
    <div class="well row">
        <form class="image-data about-text-form add-image col-md-4" method="post" action="{{ route('adminChangeAbout') }}">
            <div>
                <ul class="nav nav-tabs" role="tablist">
                    <?php $i = 0; ?>
                    @foreach(\App\Models\Language::getNativeArray() as $id => $native)
                        <li role="presentation" class="@if($i == 0) active @endif">
                            <a href="#language_{{ $id }}" aria-controls="home" role="tab" data-toggle="tab">
                                {{ $native }}
                            </a>
                        </li>
                        <?php $i++; ?>
                    @endforeach
                </ul>
                <div class="tab-content">
                    <?php $i = 0; ?>
                    @foreach(\App\Models\Language::getNativeArray() as $id => $native)
                        <div role="tabpanel" class="tab-pane @if($i == 0) active @endif" id="language_{{ $id }}">

                            <div class="form-group col-md-12">
                                <input type="text" class="form-control" name="text[{{ $id }}][{{ \App\Models\Text::KEY_ABOUT_TITLE }}]" value="{{ $texts[$id][\App\Models\Text::KEY_ABOUT_TITLE] }}" placeholder="Virsraksts">
                            </div>
                            <div class="form-group col-md-12">
                                <input type="text" class="form-control" name="text[{{ $id }}][{{ \App\Models\Text::KEY_ABOUT_QUOTE }}]" value="{{ $texts[$id][\App\Models\Text::KEY_ABOUT_QUOTE] }}" placeholder="Citāts">
                            </div>
                            <div class="form-group col-md-12">
                                <textarea type="text" rows="10" class="form-control no-resize" name="text[{{ $id }}][{{ \App\Models\Text::KEY_ABOUT_DESCRIPTION }}]" placeholder="Apraksts">{{ $texts[$id][\App\Models\Text::KEY_ABOUT_DESCRIPTION] }}</textarea>
                            </div>

                        </div>
                        <?php $i++; ?>
                    @endforeach
                </div>
                <div>
                    <div class="form-group col-md-12">
                        <input type="text" class="form-control" name="public_email" value="{{ $userData['public_email'] }}" placeholder="Epasts">
                    </div>
                    <div class="form-group col-md-12">
                        <input type="text" class="form-control" name="public_phone" value="{{ $userData['public_phone'] }}" placeholder="Tālrunis">
                    </div>
                    <div class="form-group col-md-12">
                        <input type="text" class="form-control" name="facebook_link" value="{{ $userData['facebook_link'] }}" placeholder="Facebook Adrese">
                    </div>
                    <div class="form-group col-md-12">
                        <input type="text" class="form-control" name="facebook_page_link" value="{{ $userData['facebook_page_link'] }}" placeholder="Facebook Lapas Adrese">
                    </div>
                    <div class="form-group col-md-12">
                        <input type="text" class="form-control" name="instagram_link" value="{{ $userData['instagram_link'] }}" placeholder="Instagram Adrese">
                    </div>
                    <button class="btn btn-default" type="submit">Saglabāt</button>
                </div>
            </div>
        </form>
        <div class="col-md-8">
            @include('admin.uploadImage')
        </div>
        <div class="col-md-8">
            <form class="row image-data">
                <input type="hidden" name="type" value="{{ \App\Models\Image::TYPE_AUTHOR_IMAGE }}">
                <div class="row">
                    <img src="{{ Auth::user()->getImageSource() }}" class="img-responsive col-md-12">
                </div>
            </form>
        </div>

    </div>
@stop
@include('admin.uploadAssets')

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="lv">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Edgars Vylcāns</title>

    <link href="{{ asset('/assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <link href="{{ asset('/css/app.css') }}" rel="stylesheet">

    @section('css') @show

    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png?v=1.1">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png?v=1.1">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png?v=1.1">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png?v=1.1">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png?v=1.1">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png?v=1.1">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png?v=1.1">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png?v=1.1">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png?v=1.1">
    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png?v=1.1">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png?v=1.1">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png?v=1.1">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png?v=1.1">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body class="admin @if(is_object(Route::getCurrentRoute()) && Route::getCurrentRoute()->getName() != 'home') body-margin @endif">
<div class="container">

    @if(Auth::check())
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ route('adminMain') }}">
                    <img alt="Brand" src="{{ asset('images/paraksts-small.png') }}">
                </a>
            </div>

            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ route('adminImages') }}">
                        Attēli
                    </a>
                </li>
                <li>
                    <a href="{{ route('adminCategories') }}">
                        Kategorijas
                    </a>
                </li>
                <li>
                    <a href="{{ route('adminGetAbout') }}">
                        Par mani
                    </a>
                </li>
            </ul>
            <a href="/auth/logout" class="navbar-text navbar-right logout-link">
                Iziet
            </a>
        </nav>
    @endif

    @yield('content')
</div>

<footer class="footer">
    {{ Lang::get('text.copyright_text') }} Edgars Vylcāns © {{ date('Y') }}<br>
</footer>

<!-- Scripts -->
<script src="{{ asset('/assets/jquery/jquery-1.11.3.min.js') }}"></script>
<script src="{{ asset('/assets/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/js/layout.js') }}"></script>
<script src="{{ asset('/js/app.js') }}"></script>

@section('js') @show
@section('additional_js') @show
</body>
</html>

resources/views/admin/categories.blade.php
@extends('admin.app')
@section('content')
    @if($categories->count() > 0)
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Nosaukums
                    </th>
                    <th>
                        Albumu skaits
                    </th>
                    <th>
                        Attēlu skaits
                    </th>
                    <th>
                        Skatījumi
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>
                            {{ $category->getTitle() }}
                        </td>
                        <td>
                            {{ $category->albumCount() }}
                        </td>
                        <td>
                            {{ $category->imageCount() }}
                        </td>
                        <td>
                            {{ $category->views }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif
@stop

resources/views/admin/uploadAssets.blade.php
@section('js')
    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/vendor/jquery.ui.widget.js') }}"></script>

    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/tmpl.min.js') }}"></script>
    <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/load-image.all.min.js') }}"></script>
    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/canvas-to-blob.min.js') }}"></script>

    <!-- blueimp Gallery script -->
    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/jquery.blueimp-gallery.min.js') }}"></script>

    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/jquery.iframe-transport.js') }}"></script>
    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/jquery-ui/jquery-ui.js') }}"></script>

    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/jquery.fileupload-process.js') }}"></script>

    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/jquery.fileupload-image.js') }}"></script>

    <script src="{{ asset('assets/jQuery-File-Upload-9.11.2/js/jquery.fileupload-ui.js') }}"></script>

    <script src="{{ asset('js/imageUpload.js') }}"></script>

@stop
@section('css')
    <link href="{{ asset('/assets/jQuery-File-Upload-9.11.2/css/jquery.fileupload.css') }}" rel="stylesheet">
    <link href="{{ asset('/assets/jQuery-File-Upload-9.11.2/css/style.css') }}" rel="stylesheet">
@stop

resources/views/admin/uploadImage.blade.php
<div>
    <form id="fileupload" action="{{ route('adminUpload') }}" method="POST" enctype="multipart/form-data" class="no-ajax">
        <!-- Redirect browsers with JavaScript disabled to the origin page -->
        <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>
            </div>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </form>
</div>
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
    </script>